# Generated by Django 5.2.5 on 2025-08-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_poll_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
